name: MySwiftUIApp
options:
  minimumXcodeGenVersion: 2.18.0
  xcodeVersion: "14.0"

targets:
  MySwiftUIApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources/MySwiftUIApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.MySwiftUIApp
      SWIFT_VERSION: 5.0
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
    scheme:
      testTargets:
        - MySwiftUIAppTests
      gatherCoverageData: true

  MySwiftUIAppTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests/MySwiftUIAppTests
    dependencies:
      - target: MySwiftUIApp
    settings:
      SWIFT_VERSION: 5.0
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}

schemes:
  MySwiftUIApp:
    build:
      targets:
        MySwiftUIApp: all
    test:
      targets:
        - name: MySwiftUIAppTests
          parallelizable: true
          randomExecutionOrder: true
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release 