configs:
  Debug: debug
  Release: release

name: MySwiftUIApp

options:
  bundleIdPrefix: com.seedinnovate
  deploymentTarget:
    iOS: 16.0

targetTemplates:
  app-template:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources

targets:
  MySwiftUIApp:
    templates:
      - app-template
    settings:
      base:
        PRODUCT_NAME: ${target_name}
        PRODUCT_BUNDLE_IDENTIFIER: com.seedinnovate.MySwiftUIApp
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        DEVELOPMENT_ASSET_PATHS: Resources
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_KEY_CFBundleDisplayName: ${target_name}
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        DEVELOPMENT_TEAM: 3LRSR6TS2H
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "Apple Development"
          PROVISIONING_PROFILE_SPECIFIER: ""
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "Apple Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "match AppStore com.seedinnovate.MySwiftUIApp"
