# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"],
      duration: 1200,
      in_house: false
    )

    produce(
      app_identifier: "com.seedinnovate.MySwiftUIApp",
      app_name: "MySwiftUIApp Beta",
      language: "en-US",
      app_version: "1.0",
      sku: "#{Time.now.to_i}",
      team_id: "3LRSR6TS2H"
    )

    # Increment both version and build number
    increment_version_number(
      version_number: "1.0.0" # Specify your version number here
    )
    increment_build_number # Auto-increment by 1

    match(type: "appstore", readonly: true)
    
    build_app(
      scheme: "MySwiftUIApp",
      export_method: "app-store"
    )
    
    upload_to_testflight
  end

  desc "Push a new build to TestFlight for internal testing"
  lane :internal do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"],
      duration: 1200,
      in_house: false
    )

    # Increment build number
    increment_build_number # Auto-increment by 1

    match(type: "appstore", readonly: true)
    
    build_app(
      scheme: "MySwiftUIApp",
      export_method: "app-store"
    )
    
    # Upload to TestFlight and automatically distribute to internal testers
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      distribute_external: false,
      notify_external_testers: false,
      changelog: "Internal test build",
      groups: ["Internal Testers"]
    )
  end

  desc "Add internal testers to TestFlight"
  lane :add_internal_testers do |options|
    # Ensure we have authentication set up
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"],
      duration: 1200,
      in_house: false
    )

    # Add internal testers using Spaceship
    Spaceship::ConnectAPI::BetaTester.create(
      email: options[:emails],
      first_name: options[:first_name],
      last_name: options[:last_name]
    )

    # Add tester to the Internal Testers group
    app = Spaceship::ConnectAPI::App.find("com.seedinnovate.MySwiftUIApp")
    group = Spaceship::ConnectAPI::BetaGroup.find("Internal Testers") || Spaceship::ConnectAPI::BetaGroup.create(
      name: "Internal Testers",
      app_id: app.id
    )

    tester = Spaceship::ConnectAPI::BetaTester.find_by_email(options[:emails])
    group.add_beta_tester(beta_tester_id: tester.id)
  end
end
