# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"],
      duration: 1200,
      in_house: false
    )

    produce(
      app_identifier: "com.seedinnovate.MySwiftUIApp",
      app_name: "MySwiftUIApp Beta",
      language: "en-US",
      app_version: "1.0",
      sku: "#{Time.now.to_i}",
      team_id: "3LRSR6TS2H"
    )

    # Increment both version and build number
    increment_version_number(
      version_number: "1.0.0" # Specify your version number here
    )
    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M").to_i # Use timestamp as build number
    )

    match(type: "appstore", readonly: true)
    
    build_app(
      scheme: "MySwiftUIApp",
      export_method: "app-store"
    )
    
    upload_to_testflight
  end
end
