default_platform :ios

platform :ios do
  desc "Run Unit Tests"
  lane :test do
    run_tests(
      scheme: "MySwiftUIApp",
      xcodebuild_command: "xcodebuild",
      clean: true,
      configuration: "Debug"
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    increment_build_number(
      xcodeproj: "MySwiftUIApp.xcodeproj"
    )
    build_app(
      scheme: "MySwiftUIApp",
      export_method: "app-store"
    )
    upload_to_testflight(
      username: ENV["APP_STORE_CONNECT_USERNAME"]
    )
  end
end 