name: iOS CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install XcodeGen
        run: |
          brew install xcodegen

      - name: Generate Xcode Project
        run: |
          xcodegen generate

      - name: Install Fastlane dependencies
        run: |
          gem install bundler
          bundle install || bundle update

      - name: Run tests
        run: |
          bundle exec fastlane test

  distribute:
    name: Distribute to TestFlight
    needs: [build-and-test]
    runs-on: macos-latest
    if: github.event_name == 'push'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install XcodeGen
        run: |
          brew install xcodegen

      - name: Generate Xcode Project
        run: |
          xcodegen generate

      - name: Install Fastlane dependencies
        run: |
          gem install bundler
          bundle install || bundle update

      - name: Distribute to TestFlight
        run: |
          bundle exec fastlane beta
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }} 